### ISSUE TITLE
Replace internal URLs with variables

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-ci#108]
There are few places in the `jenkins-slaves` dir where we use internal URLs. It would be preferable to replace those with variables which are then set from Jenkins/local env when actually running the packer/ansible scripts.

**Comment by mareknovotny** [comment]
@mbiarnes do you think you can look at this if we have any internal URLs in jars ?

**Comment by mbiarnes** [comment]
@mareknovotny 
what I found in jenkins-agents: 
https://docs.google.com/spreadsheets/d/1Yk8K2FQq4IpF88LoyroRZ0Q7wMGLY7_ke379V5lheO0/edit#gid=0
all other found URLs were external (10%) - so they are not listed here. It could be that in the excel are some external URLs. Feel free to remove them.
