### ISSUE TITLE
Deploy new SNAPSHOTs only if there was a change in git repo

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-ci#72]
Currently the deploy job will always deploy new SNAPSHOTs, even in cases when the code actually did not change (e.g. the build is started by an upstream job). We should investigate if it is possible to deploy the artifacts only in case the SCM changed. This would speed-up the jobs a bit in most cases and would save quite a lot of bandwidth.

**Comment by mareknovotny** [comment]
Isn't more valuable (save resources) not to trigger the job if there is no change in SCM?

**Comment by psiroky** [comment]
There are two ways the jobs are triggered: change in SCM and trigger by upstream job. When e.g. drools job finishes, it will trigger the downstream ones - jbpm and optaplanner. The upstream/downstream setup is historic and may not be needed anymore.

**Comment by mareknovotny** [comment]
thanks, I got that, so if the job trigger could be enhanced like checking if there is already successful artifact(s) with the same commit hash, the running of job could be skipped completely and save the build time.

**Comment by psiroky** [comment]
I think it still makes sense to run the build if there are upstream changes -- to make sure it still works. Potentially any upstream change can break any downstream repo. This is of course now limited with the PR builds, so it may indeed be better to just remove the upstream/downstream relation for the jobs.
